### ISSUE TITLE
bullet_threading:  broke line drawing error

### ISSUE THREAD

**Issue by cybertosher** [pengx17/logseq-dev-theme#95]
After the latest update there are small vertical lines that do not line up properly on Windows 10 machine. This was not the case on Friday, so I assume it is the latest commit to fix items on mobile platforms that did it. 

![Screenshot 2023-05-15 091018](https://github.com/pengx17/logseq-dev-theme/assets/128863536/5a1e5af3-c7fa-4e38-81a1-5d0e375f8350)

**Comment by UNICKCHENG** [comment]
If you find this issue still exists, you can try adding the following code to `logseq/custom.css` and adjusting the value of "left" to fix it.

```css
.ls-block[haschild] > div > .block-content-wrapper::before {
      left: -21px;
}
```

![image](https://github.com/pengx17/logseq-dev-theme/assets/32270702/61ed6c8a-8d5a-4aef-8614-16e5d46d6116)

**Comment by cybertosher** [comment]
Greeting! None of these worked for me. I was not using the logseq-dev-theme, I was using Bonofix before this issue started. What I tried was this:

1. I downloaded the latest dev theme (1.26.17) and verified that the custom.css file was empty. No change. 
2. I selected the dev theme as my active theme, no change.
3. I added the custom css code above and no change
4. Restarted logseq several times, no change.

So unfortunately I still have the issue with threading not working, but the additional distraction of a theme I don't like as much. :) Any ideas when or if this will be fixed, or something else I can try?

Thanks for all of your efforts.

**Comment by cybertosher** [comment]
I tried the `custom.css` code with -250px as the offset, as @MaxenceG2M  suggested, and it cleans up the issue for the bullet levels I use. I'm OK with weird artifacts that only happen sometimes. 

And I agree, thanks for all of your work @UNICKCHENG this plugin, it is definitely my favorite.

**Comment by cybertosher** [comment]
Is there going to be a permanent fix anytime soon?

**Comment by UNICKCHENG** [comment]
> Is there going to be a permanent fix anytime soon? Changing my custom.css to -15px solved the issue on my Mac, but this workaround seems a bit arbitrary. Just curious. 😃

A more universal solution than this one cannot be found at present, but I believe that this issue will eventually be resolved in the future.

**Comment by schmy** [comment]
Sorry to trouble you with this minor query, but could you please identify which line in the CSS describes the horizontal line for the child?
![image](https://github.com/pengx17/logseq-dev-theme/assets/75664705/81723fde-55fa-41fd-88b7-b281fbbbcd75)

I have already amended the line mentioned above ("ls-block ... -21 px"), but I cannot work out which other line draws to the dot point of the child lines.

Thanks in advance!

**Comment by ericz15** [comment]
Hi, I encountered the same issue and wanted to share my `custome.css` file:

```css
@import url("https://cdn.jsdelivr.net/gh/sokirill/logseq-panic-theme@main/custom.css");

:root {
    --ct-code-font-family: Maple Mono, Fira Code, Monaco, Menlo, Consolas, 'COURIER NEW', "等距更纱黑体 SC", monospace;
    --ls-font-family: Verdana, 'fira sans', 'segoe UI Emoji', 'sarasa ui sc', sans-serif;
}

#root>div,
html,
body {
    font-family: var(--ls-font-family);
}

:not(pre)>code,
.CodeMirror {
    font-family: var(--ct-code-font-family);
}
```

I've tried the solution mentioned earlier with `left: -21px;`, but unfortunately, the issue still persists.

<img width="713" alt="image" src="https://github.com/pengx17/logseq-dev-theme/assets/27724893/ac0706d7-92d4-422e-bc03-80d79537b7d6">


Thank you for your attention to this matter.

**Comment by ginko-ai** [comment]
I have similar issue, (luv the plug-in btw)
![Screenshot 2023-05-21 084244](https://github.com/pengx17/logseq-dev-theme/assets/70924243/08266fea-79bc-4030-b8c7-8e4e1631ce45)

**Comment by UNICKCHENG** [comment]
> Sorry to trouble you with this minor query, but could you please identify which line in the CSS describes the horizontal line for the child? ![image](https://user-images.githubusercontent.com/75664705/239714591-81723fde-55fa-41fd-88b7-b281fbbbcd75.png)
> 
> I have already amended the line mentioned above ("ls-block ... -21 px"), but I cannot work out which other line draws to the dot point of the child lines.
> 
> Thanks in advance!

@schmy  Try modifying the value of "right" like `right: 50px` ?

```css
.ls-block > div > div.items-center::before {
    right: 10px !important;
}
```
![image](https://github.com/pengx17/logseq-dev-theme/assets/32270702/b07bdeaa-ea65-4d89-b167-58cbdaf37c35)

**Comment by UNICKCHENG** [comment]
> I have similar issue, (luv the plug-in btw) ![Screenshot 2023-05-21 084244](https://user-images.githubusercontent.com/70924243/239752499-08266fea-79bc-4030-b8c7-8e4e1631ce45.jpg)

@ginko-ai , the issue appearing in your screenshot seems to be related to the CSS configuration of the plugin being overridden, which is causing it not to work correctly. Please refer to the following method for troubleshooting.

1. update logseq-dev-theme to the latest version, `v1.26.17`.
2. check if there are any additional configurations in the l`ogseq/custom.css` file.

**Comment by Zhangwuhao** [comment]
> I have similar issue, (luv the plug-in btw) ![Screenshot 2023-05-21 084244](https://user-images.githubusercontent.com/70924243/239752499-08266fea-79bc-4030-b8c7-8e4e1631ce45.jpg)

I have the same quesiton and how to solve this?

**Comment by UNICKCHENG** [comment]
> > I have similar issue, (luv the plug-in btw) ![Screenshot 2023-05-21 084244](https://user-images.githubusercontent.com/70924243/239752499-08266fea-79bc-4030-b8c7-8e4e1631ce45.jpg)
> 
> @ginko-ai , the issue appearing in your screenshot seems to be related to the CSS configuration of the plugin being overridden, which is causing it not to work correctly. Please refer to the following method for troubleshooting.
> 
> 1. update logseq-dev-theme to the latest version, `v1.26.17`.
> 2. check if there are any additional configurations in the `logseq/custom.css` file.

@Zhangwuhao  here ?

**Comment by Strubbl** [comment]
I have a similar issue:

![grafik](https://github.com/pengx17/logseq-dev-theme/assets/97055/78de6e64-649c-4d2c-a95d-fdbe265b2dfb)

I have no content in logseq/custom.css. This issue was fixed for me, when i installed the plugin Bullet threading. So i can reproduce the issue by deactivating that plugin.

**Comment by reprintsev** [comment]
Got the same problem after updating Logseq to version 0.9.9. Theme version v1.26.17.

Adding this code to the `custom.css` did not help

```css
.ls-block[haschild] > div > .block-content-wrapper::before {
      left: -21px;
}
```

but if I change the value of the `left` from -21px to -13px then the problem disappears.

I don't know how correct this is, but I did it and it works:

```css
.ls-block[haschild] > div > .block-content-wrapper::before {
  display: none;
}
```

**Comment by DreamWaterFound** [comment]
> Got the same problem after updating Logseq to version 0.9.9. Theme version v1.26.17.
> 
> Adding this code to the `custom.css` did not help
> 
> ```css
> .ls-block[haschild] > div > .block-content-wrapper::before {
>       left: -21px;
> }
> ```
> 
> but if I change the value of the `left` from -21px to -13px then the problem disappears.
> 
> I don't know how correct this is, but I did it and it works:
> 
> ```css
> .ls-block[haschild] > div > .block-content-wrapper::before {
>   display: none;
> }
> ```

Thanks! I also have tried to adjust the left offset but seems bad. This is work for me. Do not display the vertical dash is work for me.

**Comment by DreamWaterFound** [comment]
> > Got the same problem after updating Logseq to version 0.9.9. Theme version v1.26.17.
> > Adding this code to the `custom.css` did not help
> > ```css
> > .ls-block[haschild] > div > .block-content-wrapper::before {
> >       left: -21px;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but if I change the value of the `left` from -21px to -13px then the problem disappears.
> > I don't know how correct this is, but I did it and it works:
> > ```css
> > .ls-block[haschild] > div > .block-content-wrapper::before {
> >   display: none;
> > }
> > ```
> 
> Thanks! I also have tried to adjust the left offset but seems bad. This is work for me. Do not display the vertical dash is work for me.

Sorry, I need to apologize for my arbitrary conclusion. The method above eliminates the display of vertical lines, which exposes an issue on pages with title text. Below is the erroneous display with vertical lines:

![Screenshot from 2023-06-26 15-51-04](https://github.com/pengx17/logseq-dev-theme/assets/33981288/22b5056c-bdff-41db-a406-43dd7674f216)

Whereas the following is the result with the vertical lines removed:

![Screenshot from 2023-06-26 15-50-53](https://github.com/pengx17/logseq-dev-theme/assets/33981288/4ad2a433-955f-41b9-91b0-3a61d3096704)

So in the end, I still need to adjust the `left offset`. At the same time, I noticed an issue with the curve and bullet points not aligning closely. Thanks to @UNICKCHENG, I referred to [this reply](https://github.com/pengx17/logseq-dev-theme/issues/95#issuecomment-1556385938) and used the following code in `logseq/custom.css` to achieve a nearly perfect effect:

```css
.ls-block[haschild] > div > .block-content-wrapper::before {
      left: -13px;
}
.ls-block > div > div.items-center::before {
    right: 10px !important;
}
```

![Screenshot from 2023-06-26 15-56-01](https://github.com/pengx17/logseq-dev-theme/assets/33981288/2e8449d7-e056-4e62-835a-c366596afaeb)

I hope my experience is helpful to someone.

----
OS: ubuntu 20.04
Logseq: 0.9.9
logseq-dev-theme: 1.26.17

**Comment by UdeRecife** [comment]
I have the same issue. Unfortunately, none of the solutions above work. The fixes always break at some level of indentation. And I use a LOT of indentation.

**Comment by cybertosher** [comment]
Broken again. I have logseq 0.10.7 and the latest dev theme, and once again there is a little broken line. No configuration in custom.css. Is the best way to fix this one again to add the custom CSS, or is there an error with the theme maybe that fixes it? I do no have this issue on Windows 10, only MacOS

**Comment by cybertosher** [comment]
The plugin seems to be working fine, my issue is with the theme.
